#Transforming Vectors

In [15]:

#Transformimg Vectors
import numpy as np

# Define the vector
vector = np.array([1, 2, 3])

# Define the transformation matrix
transformation_matrix = np.array([[2, 0, 0],
                                  [0, 3, 0],
                                  [0, 0, 4]])

# Apply the transformation
transformed_vector = np.dot(transformation_matrix, vector)

# Print the transformed vector
print(transformed_vector)

[ 2  6 12]


Matrix

In [2]:
import numpy as np

# Creating a 2x3 matrix from a list of lists
matrix_list = [[1, 2, 3],
              [4, 5, 6]]

matrix_np = np.array(matrix_list)
print(matrix_np)

[[1 2 3]
 [4 5 6]]


#Addition in Matrix.

In [4]:
import numpy as np

# Define two matrices
matrix1 = np.array([[1, 2],
                   [3, 4]])

matrix2 = np.array([[5, 6],
                   [7, 8]])

# Perform matrix addition using np.add()
result_matrix = np.add(matrix1, matrix2)
print("Result of Matrix Addition using np.add():")
print(result_matrix)

Result of Matrix Addition using np.add():
[[ 6  8]
 [10 12]]


In [3]:
import numpy as np

# Define two matrices
matrix1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

matrix2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

# Perform element-wise addition
result_matrix = matrix1 + matrix2
print("Result of Element-wise Addition:")
print(result_matrix)

Result of Element-wise Addition:
[[ 8 10 12]
 [14 16 18]]


#Subtraction in Matrix

In [6]:
import numpy as np

# Define two matrices
matrix1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

matrix2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

# Perform element-wise subtraction
result_matrix = matrix1 - matrix2
print("Result of Element-wise Subtraction:")
print(result_matrix)

Result of Element-wise Subtraction:
[[-6 -6 -6]
 [-6 -6 -6]]


In [8]:
import numpy as np

# Define two matrices
matrix1 = np.array([[1, 2],
                   [3, 4]])

matrix2 = np.array([[5, 6],
                   [7, 8]])

# Perform matrix subtraction using np.subtract()
result_matrix = np.subtract(matrix1, matrix2)
print("Result of Matrix Subtraction using np.subtract():")
print(result_matrix)

Result of Matrix Subtraction using np.subtract():
[[-4 -4]
 [-4 -4]]


#Multiplication of Matrixes

In [ ]:
#multiply : element wise matrix multiplication
#matmul   : matrix product of two arrays
#dot      : dot products of two arrays

In [9]:
import numpy as np

arr1 = np.array([[1, 2],
                 [3, 4]])
arr2 = np.array([[5, 6],
                 [7, 8]])

arr_result = np.multiply(arr1, arr2)

print(arr_result)

[[ 5 12]
 [21 32]]


In [10]:
import numpy as np

arr1 = np.array([[1, 2],
                 [3, 4]])
arr2 = np.array([[5, 6],
                 [7, 8]])

arr_result = np.matmul(arr1, arr2)

print(f'Matrix Product of arr1 and arr2 is:\n{arr_result}')

arr_result = np.matmul(arr2, arr1)


Matrix Product of arr1 and arr2 is:
[[19 22]
 [43 50]]


In [11]:
import numpy as np

arr1 = np.array([[1, 2],
                 [3, 4]])
arr2 = np.array([[5, 6],
                 [7, 8]])

arr_result = np.dot(arr1, arr2)

print(f'Dot Product of arr1 and arr2 is:\n{arr_result}')

arr_result = np.dot(arr2, arr1)

print(f'Dot Product of arr2 and arr1 is:\n{arr_result}')


Dot Product of arr1 and arr2 is:
[[19 22]
 [43 50]]
Dot Product of arr2 and arr1 is:
[[23 34]
 [31 46]]


In [ ]:
#REFERENCES

#https://www.digitalocean.com/community/tutorials/numpy-matrix-multiplication